import { CustomForm } from './CustomForm'

const dataPart = [

    {
        span:"POUR LES ENTREPRISES",
        h1:"Conçu avec les entreprises, pour les entreprises",
        p:"Slack est sécurisé. Modulable. C’est un logiciel que les personnes aiment utiliser, qui est disponible pour aider votre entreprise. Découvrez comment Slack soutient les entreprises de toutes tailles :",
        li:["ÉVOLUTIVITÉ","SÉCURITÉ","INVESTISSEMENT PERSONNEL","PLATEFORME","SLACK CONNECT"],
        lien:{text:"Contactez-Nous", href:"#",page:"contact",type:"button",class:"ui button big primary",style:{margin:"20px"}},
        p2: "",
        logos:[""],
        p3:"",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/hero/enterprise-hero.fr-FR.jpg",
        page:"contact"
        
    },
    {
        span:"ÉVOLUTIVITÉ",
        h1:"Créé pour répondre aux besoins des entreprises internationales",
        p:"",
        li:["Soyez tranquille grâce à un temps de fonctionnement optimal de 99,99 %.",
        "Personnalisez Slack pour votre entreprise grâce à un nombre illimité de d’espaces de travail et de canauxÉ",
        "Gérez tous vos utilisateurs et équipes de manière centralisée"],
        lien:{text:"En savoir plus sur Slack", href:"#",type:"button"},
        p2: "« Slack nous a permis de décloisonner. Nous avons adopté Slack comme système de collaboration dans 194 pays et 171 bureaux différents, et l’esprit d’équipe n’a jamais été aussi fort. »",
        logos:["./img/fox.png"],
        p3:"Jeff Dow, vice-président exécutif des opérations médiatiques et de diffusion",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/sections/1-scale/scale.fr-FR.jpg"
    },
    {
        span:"SÉCURITÉ",
        h1:"Haut niveau de protection des données",
        p:"",
        li:["Répondez aux exigences de conformité et aux exigences réglementaires comme la FINRA, la HIPAA et la FedRAMP",
        "Soyez rassuré(e), Slack utilise les meilleures pratiques et dispositifs reconnus par l’industrie",
        "Sécurisez vos données grâce à des fonctionnalités innovantes comme la gestion des clés de chiffrement Slack Enterprise (Slack EKM)"],
        lien:{text:"En savoir plus sur la sécurité", href:"#",type:"button"},
        p2: "« En renforçant notre sécurité avec la gestion des clés de chiffrement Slack Entreprise, nous avons immédiatement compris la valeur ajoutée de cette fonctionnalité qui nous offrait un contrôle total de nos données et la garantie que nous étions protégés en cas de menace de sécurité au sein de notre chaîne d’approvisionnement. »",
        logos:["./img/crowdstrike.png"],
        p3:"Colin Black, Opérateur en chef",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/sections/2-security/security.fr-FR.jpg"
    },
    {
        span:"INVESTISSEMENT PERSONNEL",
        h1:"L’engagement est un meilleur indicateur que le nombre d’installations",
        p:"",
        li:["Travaillez de la façon qui vous convient le mieux grâce à une expérience utilisateur simple et intuitive",
        "Automatisez les tâches quotidiennes grâce à des flux de travail personnalisés, sans avoir besoin de les coder",
        "Suivez vos projets où que vous soyez, sur mobile ou sur votre ordinateur"],
        lien:{text:"Découvrir comment Slack génère de l’engagement", href:"#",type:"button"},
        p2: "",
        logos:["./img/idc.png","./img/td-ameritrade.png"],
        p3:"¹Source : « La valeur commerciale de Slack ComputerWorld, « TD Ameritrade cuts email use by 30% after Slack rollout », 2019",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/sections/3-engagement/engagement.fr-FR.jpg"
    },
    {
        span:"PLATEFORME",
        h1:"Des applis qui dopent la productivité et s’adaptent à votre utilisation",
        p:"",
        li:["Assurez-vous de la conformité des applis tierces",
        "Standardisez les autorisations d’applis dans votre entreprise",
        "Choisissez parmi plus de 2 400 applications"],
        lien:{text:"En savoir plus sur les applications et les intégrations", href:"#",type:"button"},
        p2: "",
        logos:["./img/logosP/zoom.png","./img/logosP/outlook.png","./img/logosP/google-drive.png","./img/logosP/salesforce.png","./img/logosP/service-now.png","./img/logosP/onedrive.png","./img/logosP/gmail.png","./img/logosP/dropbox.png"],
        p3:"",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/hero/enterprise-hero.fr-FR.jpg"
    },
    {
        span:"SLACK CONNECT",
        h1:"Travaillez avec des partenaires externes en toute sécurité",
        p:"",
        li:["Conservez vos pratiques de sécurité des données tout en collaborant avec des partenaires de confiance",
        "Connectez-vous à vos collaborateurs, clients et partenaires de manière centralisée",
        "Réduisez les changements d’environnement de travail, augmentez la transparence et la productivité"],
        lien:{text:"Découvrez le fonctionnement de Slack Connect", href:"#",type:"button"},
        p2: "« Pour nous, il est essentiel que toutes les informations concernant un partenaire soient immédiatement à portée de main. Nous disposons d’une ligne directe avec nos homologues au sein des entreprises avec lesquelles nous collaborons le plus souvent. »",
        logos:["./img/zendesk.png"],
        p3:"Mike Yakovlev, directeur des alliances technologiques",
        imgSrc:"https://a.slack-edge.com/379ae/marketing/img/enterprise/new/sections/5-connect/slack-connect.fr-FR.jpg"
    }
]

export const logos =[
    "./img/deezer.png",
    "./img/airbnb-logo.png",
    "./img/criteo.png",
    "./img/le-monde.png",
    "./img/blablacar.png",
    "./img/m6.png",
    "./img/veepee.png",
]

export const dataFoire = [
    {
        title:"Slack est-il sécurisé ?", 
        content:"Oui, vous pouvez discuter d’informations confidentielles dans Slack, en toute sécurité. Slack dispose de nombreuses fonctionnalités qui garantissent la sécurité de vos informations, conversations et fichiers. Slack offre un niveau de sécurité professionnel pour tous les secteurs de votre entreprise, en adhérant à plusieurs certifications de conformité, notamment SOC 2, SOC 3, ISO/IEC 27001 et plus encore. Slack est conforme au RGPD et peut être configuré pour l’être également à la HIPAA et à la FINRA. Slack bénéficie de l’autorisation FedRAMP Moderate. Slack propose également des fonctionnalités de sécurité, comme la gestion des clés de chiffrement Slack Enterprise (Slack EKM), qui permettent aux administrateurs d’avoir le contrôle intégral du chiffrement des données. Vous pouvez également intégrer vos propres outils de sécurité à Slack pour être notifié instantanément de toute menace. Découvrez-en plus sur le programme de sécurité détaillé de Slack ici."
     },
     {
        title:"Qu’est-ce qu’Enterprise Grid ?", 
        content:"Slack a conçu Entreprise Grid pour répondre aux besoins des grands groupes. C’est la solution qui vous permet de travailler avec la même agilité qu’une petite entreprise, tout en tirant parti de vos ressources et connaissances partagées. Enterprise Grid comprend toutes les fonctionnalités de sécurité et de gestion que l’on peut attendre d’une solution d’entreprise, tout en offrant une expérience conviviale et intuitive qui favorise l’adoption. De grandes entreprises du monde entier, comme IBM, Condé Nast, Oracle et E-Trade, utilisent déjà Enterprise Grid. Il s’agit du seul produit de collaboration capable de prendre en charge jusqu’à 500 000 personnes. Enterprise Grid est un forfait payant. Comparez les fonctionnalités et tarifs de nos forfais ici."
     },
     {
        title:"Slack est-il plus sécurisé que les e-mails ?", 
        content:"Tout à fait ! Contrairement aux e-mails, Slack évite le spam ou le phishing, responsables de 90 % des failles de sécurité. Votre identifiant Slack ne peut ni être vendu à des annonceurs, ni inscrit sur une liste de diffusion. Vous ne recevrez des messages que de la part des personnes de votre entreprise, ou de vos partenaires de confiance qui utilisent Slack Connect. Vous pourrez également recevoir des notifications d’applis intégrées à votre espace de travail comme Asana, Google Docs ou Jira.bSlack garantit une protection et une confidentialité de vos données adaptées aux entreprises. Le contrôle granulaire permet aux administrateurs de paramétrer les niveaux de sécurité pour chaque utilisateur, afin que chacun ait accès aux données lui étant réservées. Découvrez pourquoi Slack est la solution de sécurité permettant de remplacer les e-mails au sein de votre compagnie."
     },
     {
        title:"Qu’est-ce qu’un canal Slack ?", 
        content:"Dans Slack, les canaux sont au cœur du travail. Un canal permet à une équipe de centraliser et de partager des messages, des outils et des fichiers. Les personnes créent généralement des canaux pour les annonces propres à l’entreprise, pour la gestion de l’assistance clientèle, pour communiquer avec les ressources humaines ou les services informatiques et pour partager leurs centres d’intérêt. Les canaux peuvent être publics (ouverts à tous les salariés de l’entreprise) ou privés (sur invitation uniquement). De plus, les entreprises ayant souscrit à un forfait payant Slack peuvent partager un canal avec des partenaires externes comme des agences, des clients et des fournisseurs grâce à Slack Connect. Découvrez comment les canaux peuvent augmenter votre productivité ici."
     },
     {
        title:"Comment les entreprises utilisent-elles Slack ?", 
        content:"Slack aide les entreprises à rassembler leurs salariés et leurs outils en un seul et même endroit, afin qu’ils restent productifs et en harmonie, où qu’ils soient. Plus de 750 000 entreprises utilisent Slack au quotidien pour communiquer, partager des fichiers et passer des appels audio et vidéo. Vous pouvez y intégrer des milliers d’outils, comme Google Drive, Zoom ou Salesforce, ou concevoir des bots ou des applis spécialement pour votre entreprise. En savoir plus sur le fonctionnement de Slack ici."
     },
     {
        title:"Qu’est-ce que Slack Connect ?", 
        content:"Slack Connect est un moyen sécurisé et efficace pour les entreprises de communiquer entre elles. En l’utilisant, vous pouvez déplacer toutes les conversations avec vos partenaires, clients et fournisseurs externes dans Slack, remplaçant ainsi les e-mails et favorisant la collaboration. Les fonctionnalités de sécurité et les standards de conformité de niveau professionnel de Slack, comme la gestion des clés de chiffrement Slack Enterprise (Slack EKM), s’étendent à Slack Connect. Découvrez plus d’informations sur Slack Connect ici."
     },
]


export const dataCard = [
    {
        meta:"Slack est-il sécurisé ?", 
        content:"ManoMano et Voodoo : préserver sa culture à distance avec Slack",
        lien:"#",
        src:"https://a.slack-edge.com/fd4d6a1/marketing/img/enterprise/new/promos/voodoo_1_FR.jpg"
    },
     {
        meta:"Conférence en ligne", 
        content:"Libérez-vous des e-mails : le témoignage d’Aircall",
        lien:"#",
        src:"https://a.slack-edge.com/fd4d6a1/marketing/img/enterprise/new/promos/Asset_2_FR.jpg"
    },
     {
        meta:"Témoignages de clients", 
        content:"Comment Veepee, la licorne du e-commerce, a diminué ses incidents de 67 % avec Slack",
        lien:"#",
        src:"https://a.slack-edge.com/fd4d6a1/marketing/img/enterprise/new/promos/veepee_fr.jpg"
 
    },
  
]

export const dataFooterInfos =[
    "Adoptez une nouvelle façon de travailler",
    "CONTACTER NOTRE ÉQUIPE COMMERCIALE",
    "2022 Slack Technologies, LLC, une entreprise Salesforce. Tous droits réservés. Les différentes marques commerciales appartiennent à leurs propriétaires respectifs."
]


export const dataFooter = [
    [
    "POURQUOI CHOISIR SLACK ?",
    "Comparatif Slack vs. E-mail",
    "Canaux",
    "Investissement personnel",
    "Évolutivité",
    "Regarder la démonstration",
    ],
    ["PRODUIT",
    "Fonctionnalités",
    "Intégrations",
    "Pour les entreprises",
    "Solutions",
    ],
    ["TARIFS",
    "Forfaits",
    "Payant vs. Gratuit",
    "",
    "",
    ],
    ["RESSOURCES",
    "Partenaires",
    "Développeurs",
    "Communauté",
    "Applications",
    "Blog",
    "Centre d’assistance",
    "Événements",
    ],
    ["À PROPOS DE SLACK",
    "À propos de nous",
    "Nos dirigeants",
    "Relations avec les investisseurs",
    "Actualités",
    "Dossier de presse",
    "Emplois",
    ]
]

export const dataPartContact = [

    {
        span:"",
        h1:"Contacter notre equipe commerciale",
        p:"Nous sommes ravis de répondre à vos questions et de vous présenter Slack.",
        li:["Découvrir comment augmenter la productivité de vos équipes","Recevoir des informations tarifaires","Découvrir des cas d’utilisation pour votre équipe"],
        lien:{text:"vous rendre sur notre centre d’assistance", href:"#",type:"",class:"",style:{margin:"20px"},textContact:"Pour toute question technique et demande générale, veuillez"},
        p2: "« Slack a révolutionné notre manière de travailler, [c'est] le canal de communication préféré dans notre entreprise, et le seul que nous apprécions réellement. [...] Slack est tout sauf rigide dans son utilisation, nous l'avons personnalisé intégralement afin qu’il réponde à nos besoins. »",
        logos:["./img/deliveroo.png"],
        p3:"Will Sprunt <br/> Directeur des systèmes d’information, Deliveroo",
        form:" <CustomForm />",
        page:"contact"
        
    },]

export const pays = [
        { text: 'Afghanistan', key: 'af',value: 'af', flag: 'af' },
        { text: 'Aland Islands', key: 'ax',value: 'ax', flag: 'ax' },
        { text: 'Albania', key: 'al',value: 'al', flag: 'al' },
        { text: 'Algeria', key: 'dz',value: 'dz', flag: 'dz' },
        { text: 'American Samoa', key: 'as',value: 'as', flag: 'as' },
        { text: 'Andorra', key: 'ad',value: 'ad', flag: 'ad' },
        { text: 'Angola', key: 'ao',value: 'ao', flag: 'ao' },
        { text: 'Anguilla', key: 'ai',value: 'ai', flag: 'ai' },
        { text: 'Antigua', key: 'ag',value: 'ag', flag: 'ag' },
        { text: 'Argentina', key: 'ar',value: 'ar', flag: 'ar' },
        { text: 'Armenia', key: 'am',value: 'am', flag: 'am' },
        { text: 'Aruba', key: 'aw',value: 'aw', flag: 'aw' },
        { text: 'Australia', key: 'au',value: 'au', flag: 'au' },
        { text: 'Austria', key: 'at',value: 'at', flag: 'at' },
        { text: 'Azerbaijan', key: 'az',value: 'az', flag: 'az' },
        { text: 'Bahamas', key: 'bs',value: 'bs', flag: 'bs' },
        { text: 'Bahrain', key: 'bh',value: 'bh', flag: 'bh' },
        { text: 'Bangladesh', key: 'bd',value: 'bd', flag: 'bd' },
        { text: 'Barbados', key: 'bb',value: 'bb', flag: 'bb' },
        { text: 'Belarus', key: 'by',value: 'by', flag: 'by' },
        { text: 'Belgium', key: 'be',value: 'be', flag: 'be' },
        { text: 'Belize', key: 'bz',value: 'bz', flag: 'bz' },
        { text: 'Benin', key: 'bj',value: 'bj', flag: 'bj' },
        { text: 'Bermuda', key: 'bm',value: 'bm', flag: 'bm' },
        { text: 'Bhutan', key: 'bt',value: 'bt', flag: 'bt' },
        { text: 'Bolivia', key: 'bo',value: 'bo', flag: 'bo' },
        { text: 'Bosnia', key: 'ba',value: 'ba', flag: 'ba' },
        { text: 'Botswana', key: 'bw',value: 'bw', flag: 'bw' },
        { text: 'Bouvet Island', key: 'bv',value: 'bv', flag: 'bv' },
        { text: 'Brazil', key: 'br',value: 'br', flag: 'br' },
        { text: 'British Virgin Islands', key: 'vg',value: 'vg', flag: 'vg' },
        { text: 'Brunei', key: 'bn',value: 'bn', flag: 'bn' },
        { text: 'Bulgaria', key: 'bg',value: 'bg', flag: 'bg' },
        { text: 'Burkina Faso', key: 'bf',value: 'bf', flag: 'bf' },
        { text: 'Burma', key: 'mm',value: 'mm', flag: 'mm', alias: 'Myanmar' },
        { text: 'Burundi', key: 'bi',value: 'bi', flag: 'bi' },
        { text: 'Caicos Islands', key: 'tc',value: 'tc', flag: 'tc' },
        { text: 'Cambodia', key: 'kh',value: 'kh', flag: 'kh' },
        { text: 'Cameroon', key: 'cm',value: 'cm', flag: 'cm' },
        { text: 'Canada', key: 'ca',value: 'ca', flag: 'ca' },
        { text: 'Cape Verde', key: 'cv',value: 'cv', flag: 'cv' },
        { text: 'Cayman Islands', key: 'ky',value: 'ky', flag: 'ky' },
        { text: 'Central African Republic', key: 'cf',value: 'cf', flag: 'cf' },
        { text: 'Chad', key: 'td',value: 'td', flag: 'td' },
        { text: 'Chile', key: 'cl',value: 'cl', flag: 'cl' },
        { text: 'China', key: 'cn',value: 'cn', flag: 'cn' },
        { text: 'Christmas Island', key: 'cx',value: 'cx', flag: 'cx' },
        { text: 'Cocos Islands', key: 'cc',value: 'cc', flag: 'cc' },
        { text: 'Colombia', key: 'co',value: 'co', flag: 'co' },
        { text: 'Comoros', key: 'km',value: 'km', flag: 'km' },
        { text: 'Congo', key: 'cd',value: 'cd', flag: 'cd' },
        { text: 'Congo Brazzaville', key: 'cg',value: 'cg', flag: 'cg' },
        { text: 'Cook Islands', key: 'ck',value: 'ck', flag: 'ck' },
        { text: 'Costa Rica', key: 'cr',value: 'cr', flag: 'cr' },
        { text: 'Cote Divoire', key: 'ci',value: 'ci', flag: 'ci' },
        { text: 'Croatia', key: 'hr',value: 'hr', flag: 'hr' },
        { text: 'Cuba', key: 'cu',value: 'cu', flag: 'cu' },
        { text: 'Cyprus', key: 'cy',value: 'cy', flag: 'cy' },
        { text: 'Czech Republic', key: 'cz',value: 'cz', flag: 'cz' },
        { text: 'Denmark', key: 'dk',value: 'dk', flag: 'dk' },
        { text: 'Djibouti', key: 'dj',value: 'dj', flag: 'dj' },
        { text: 'Dominica', key: 'dm',value: 'dm', flag: 'dm' },
        { text: 'Dominican Republic', key: 'do',value: 'do', flag: 'do' },
        { text: 'Ecuador', key: 'ec',value: 'ec', flag: 'ec' },
        { text: 'Egypt', key: 'eg',value: 'eg', flag: 'eg' },
        { text: 'El Salvador', key: 'sv',value: 'sv', flag: 'sv' },
        { text: 'Equatorial Guinea', key: 'gq',value: 'gq', flag: 'gq' },
        { text: 'Eritrea', key: 'er',value: 'er', flag: 'er' },
        { text: 'Estonia', key: 'ee',value: 'ee', flag: 'ee' },
        { text: 'Ethiopia', key: 'et',value: 'et', flag: 'et' },
        { text: 'Europeanunion', key: 'eu',value: 'eu', flag: 'eu' },
        { text: 'Falkland Islands', key: 'fk',value: 'fk', flag: 'fk' },
        { text: 'Faroe Islands', key: 'fo',value: 'fo', flag: 'fo' },
        { text: 'Fiji', key: 'fj',value: 'fj', flag: 'fj' },
        { text: 'Finland', key: 'fi',value: 'fi', flag: 'fi' },
        { text: 'France', key: 'fr',value: 'fr', flag: 'fr' },
        { text: 'French Guiana', key: 'gf',value: 'gf', flag: 'gf' },
        { text: 'French Polynesia', key: 'pf',value: 'pf', flag: 'pf' },
        { text: 'French Territories', key: 'tf',value: 'tf', flag: 'tf' },
        { text: 'Gabon', key: 'ga',value: 'ga', flag: 'ga' },
        { text: 'Gambia', key: 'gm',value: 'gm', flag: 'gm' },
        { text: 'Georgia', key: 'ge',value: 'ge', flag: 'ge' },
        { text: 'Germany', key: 'de',value: 'de', flag: 'de' },
        { text: 'Ghana', key: 'gh',value: 'gh', flag: 'gh' },
        { text: 'Gibraltar', key: 'gi',value: 'gi', flag: 'gi' },
        { text: 'Greece', key: 'gr',value: 'gr', flag: 'gr' },
        { text: 'Greenland', key: 'gl',value: 'gl', flag: 'gl' },
        { text: 'Grenada', key: 'gd',value: 'gd', flag: 'gd' },
        { text: 'Guadeloupe', key: 'gp',value: 'gp', flag: 'gp' },
        { text: 'Guam', key: 'gu',value: 'gu', flag: 'gu' },
        { text: 'Guatemala', key: 'gt',value: 'gt', flag: 'gt' },
        { text: 'Guinea', key: 'gn',value: 'gn', flag: 'gn' },
        { text: 'Guinea-Bissau', key: 'gw',value: 'gw', flag: 'gw' },
        { text: 'Guyana', key: 'gy',value: 'gy', flag: 'gy' },
        { text: 'Haiti', key: 'ht',value: 'ht', flag: 'ht' },
        { text: 'Heard Island', key: 'hm',value: 'hm', flag: 'hm' },
        { text: 'Honduras', key: 'hn',value: 'hn', flag: 'hn' },
        { text: 'Hong Kong', key: 'hk',value: 'hk', flag: 'hk' },
        { text: 'Hungary', key: 'hu',value: 'hu', flag: 'hu' },
        { text: 'Iceland', key: 'is',value: 'is', flag: 'is' },
        { text: 'India', key: 'in',value: 'in', flag: 'in' },
        { text: 'Indian Ocean Territory', key: 'io',value: 'io', flag: 'io' },
        { text: 'Indonesia', key: 'id',value: 'id', flag: 'id' },
        { text: 'Iran', key: 'ir',value: 'ir', flag: 'ir' },
        { text: 'Iraq', key: 'iq',value: 'iq', flag: 'iq' },
        { text: 'Ireland', key: 'ie',value: 'ie', flag: 'ie' },
        { text: 'Israel', key: 'il',value: 'il', flag: 'il' },
        { text: 'Italy', key: 'it',value: 'it', flag: 'it' },
        { text: 'Jamaica', key: 'jm',value: 'jm', flag: 'jm' },
        { text: 'Jan Mayen', key: 'sj',value: 'sj', flag: 'sj', alias: 'Svalbard' },
        { text: 'Japan', key: 'jp',value: 'jp', flag: 'jp' },
        { text: 'Jordan', key: 'jo',value: 'jo', flag: 'jo' },
        { text: 'Kazakhstan', key: 'kz',value: 'kz', flag: 'kz' },
        { text: 'Kenya', key: 'ke',value: 'ke', flag: 'ke' },
        { text: 'Kiribati', key: 'ki',value: 'ki', flag: 'ki' },
        { text: 'Kuwait', key: 'kw',value: 'kw', flag: 'kw' },
        { text: 'Kyrgyzstan', key: 'kg',value: 'kg', flag: 'kg' },
        { text: 'Laos', key: 'la',value: 'la', flag: 'la' },
        { text: 'Latvia', key: 'lv',value: 'lv', flag: 'lv' },
        { text: 'Lebanon', key: 'lb',value: 'lb', flag: 'lb' },
        { text: 'Lesotho', key: 'ls',value: 'ls', flag: 'ls' },
        { text: 'Liberia', key: 'lr',value: 'lr', flag: 'lr' },
        { text: 'Libya', key: 'ly',value: 'ly', flag: 'ly' },
        { text: 'Liechtenstein', key: 'li',value: 'li', flag: 'li' },
        { text: 'Lithuania', key: 'lt',value: 'lt', flag: 'lt' },
        { text: 'Luxembourg', key: 'lu',value: 'lu', flag: 'lu' },
        { text: 'Macau', key: 'mo',value: 'mo', flag: 'mo' },
        { text: 'Macedonia', key: 'mk',value: 'mk', flag: 'mk' },
        { text: 'Madagascar', key: 'mg',value: 'mg', flag: 'mg' },
        { text: 'Malawi', key: 'mw',value: 'mw', flag: 'mw' },
        { text: 'Malaysia', key: 'my',value: 'my', flag: 'my' },
        { text: 'Maldives', key: 'mv',value: 'mv', flag: 'mv' },
        { text: 'Mali', key: 'ml',value: 'ml', flag: 'ml' },
        { text: 'Malta', key: 'mt',value: 'mt', flag: 'mt' },
        { text: 'Marshall Islands', key: 'mh',value: 'mh', flag: 'mh' },
        { text: 'Martinique', key: 'mq',value: 'mq', flag: 'mq' },
        { text: 'Mauritania', key: 'mr',value: 'mr', flag: 'mr' },
        { text: 'Mauritius', key: 'mu',value: 'mu', flag: 'mu' },
        { text: 'Mayotte', key: 'yt',value: 'yt', flag: 'yt' },
        { text: 'Mexico', key: 'mx',value: 'mx', flag: 'mx' },
        { text: 'Micronesia', key: 'fm',value: 'fm', flag: 'fm' },
        { text: 'Moldova', key: 'md',value: 'md', flag: 'md' },
        { text: 'Monaco', key: 'mc',value: 'mc', flag: 'mc' },
        { text: 'Mongolia', key: 'mn',value: 'mn', flag: 'mn' },
        { text: 'Montenegro', key: 'me',value: 'me', flag: 'me' },
        { text: 'Montserrat', key: 'ms',value: 'ms', flag: 'ms' },
        { text: 'Morocco', key: 'ma',value: 'ma', flag: 'ma' },
        { text: 'Mozambique', key: 'mz',value: 'mz', flag: 'mz' },
        { text: 'Namibia', key: 'na',value: 'na', flag: 'na' },
        { text: 'Nauru', key: 'nr',value: 'nr', flag: 'nr' },
        { text: 'Nepal', key: 'np',value: 'np', flag: 'np' },
        { text: 'Netherlands', key: 'nl',value: 'nl', flag: 'nl' },
        { text: 'Netherlandsantilles', key: 'an',value: 'an', flag: 'an' },
        { text: 'New Caledonia', key: 'nc',value: 'nc', flag: 'nc' },
        { text: 'New Guinea', key: 'pg',value: 'pg', flag: 'pg' },
        { text: 'New Zealand', key: 'nz',value: 'nz', flag: 'nz' },
        { text: 'Nicaragua', key: 'ni',value: 'ni', flag: 'ni' },
        { text: 'Niger', key: 'ne',value: 'ne', flag: 'ne' },
        { text: 'Nigeria', key: 'ng',value: 'ng', flag: 'ng' },
        { text: 'Niue', key: 'nu',value: 'nu', flag: 'nu' },
        { text: 'Norfolk Island', key: 'nf',value: 'nf', flag: 'nf' },
        { text: 'North Korea', key: 'kp',value: 'kp', flag: 'kp' },
        { text: 'Northern Mariana Islands', key: 'mp',value: 'mp', flag: 'mp' },
        { text: 'Norway', key: 'no',value: 'no', flag: 'no' },
        { text: 'Oman', key: 'om',value: 'om', flag: 'om' },
        { text: 'Pakistan', key: 'pk',value: 'pk', flag: 'pk' },
        { text: 'Palau', key: 'pw',value: 'pw', flag: 'pw' },
        { text: 'Palestine', key: 'ps',value: 'ps', flag: 'ps' },
        { text: 'Panama', key: 'pa',value: 'pa', flag: 'pa' },
        { text: 'Paraguay', key: 'py',value: 'py', flag: 'py' },
        { text: 'Peru', key: 'pe',value: 'pe', flag: 'pe' },
        { text: 'Philippines', key: 'ph',value: 'ph', flag: 'ph' },
        { text: 'Pitcairn Islands', key: 'pn',value: 'pn', flag: 'pn' },
        { text: 'Poland', key: 'pl',value: 'pl', flag: 'pl' },
        { text: 'Portugal', key: 'pt',value: 'pt', flag: 'pt' },
        { text: 'Puerto Rico', key: 'pr',value: 'pr', flag: 'pr' },
        { text: 'Qatar', key: 'qa',value: 'qa', flag: 'qa' },
        { text: 'Reunion', key: 're',value: 're', flag: 're' },
        { text: 'Romania', key: 'ro',value: 'ro', flag: 'ro' },
        { text: 'Russia', key: 'ru',value: 'ru', flag: 'ru' },
        { text: 'Rwanda', key: 'rw',value: 'rw', flag: 'rw' },
        { text: 'Saint Helena', key: 'sh',value: 'sh', flag: 'sh' },
        { text: 'Saint Kitts and Nevis', key: 'kn',value: 'kn', flag: 'kn' },
        { text: 'Saint Lucia', key: 'lc',value: 'lc', flag: 'lc' },
        { text: 'Saint Pierre', key: 'pm',value: 'pm', flag: 'pm' },
        { text: 'Saint Vincent', key: 'vc',value: 'vc', flag: 'vc' },
        { text: 'Samoa', key: 'ws',value: 'ws', flag: 'ws' },
        { text: 'San Marino', key: 'sm',value: 'sm', flag: 'sm' },
        { text: 'Sandwich Islands', key: 'gs',value: 'gs', flag: 'gs' },
        { text: 'Sao Tome', key: 'st',value: 'st', flag: 'st' },
        { text: 'Saudi Arabia', key: 'sa',value: 'sa', flag: 'sa' },

        { text: 'Senegal', key: 'sn',value: 'sn', flag: 'sn' },
        { text: 'Serbia', key: 'cs',value: 'cs', flag: 'cs' },
        { text: 'Serbia', key: 'rs',value: 'rs', flag: 'rs' },
        { text: 'Seychelles', key: 'sc',value: 'sc', flag: 'sc' },
        { text: 'Sierra Leone', key: 'sl',value: 'sl', flag: 'sl' },
        { text: 'Singapore', key: 'sg',value: 'sg', flag: 'sg' },
        { text: 'Slovakia', key: 'sk',value: 'sk', flag: 'sk' },
        { text: 'Slovenia', key: 'si',value: 'si', flag: 'si' },
        { text: 'Solomon Islands', key: 'sb',value: 'sb', flag: 'sb' },
        { text: 'Somalia', key: 'so',value: 'so', flag: 'so' },
        { text: 'South Africa', key: 'za',value: 'za', flag: 'za' },
        { text: 'South Korea', key: 'kr',value: 'kr', flag: 'kr' },
        { text: 'Spain', key: 'es',value: 'es', flag: 'es' },
        { text: 'Sri Lanka', key: 'lk',value: 'lk', flag: 'lk' },
        { text: 'Sudan', key: 'sd',value: 'sd', flag: 'sd' },
        { text: 'Suritext', key: 'sr',value: 'sr', flag: 'sr' },
        { text: 'Swaziland', key: 'sz',value: 'sz', flag: 'sz' },
        { text: 'Sweden', key: 'se',value: 'se', flag: 'se' },
        { text: 'Switzerland', key: 'ch',value: 'ch', flag: 'ch' },
        { text: 'Syria', key: 'sy',value: 'sy', flag: 'sy' },
        { text: 'Taiwan', key: 'tw',value: 'tw', flag: 'tw' },
        { text: 'Tajikistan', key: 'tj',value: 'tj', flag: 'tj' },
        { text: 'Tanzania', key: 'tz',value: 'tz', flag: 'tz' },
        { text: 'Thailand', key: 'th',value: 'th', flag: 'th' },
        { text: 'Timorleste', key: 'tl',value: 'tl', flag: 'tl' },
        { text: 'Togo', key: 'tg',value: 'tg', flag: 'tg' },
        { text: 'Tokelau', key: 'tk',value: 'tk', flag: 'tk' },
        { text: 'Tonga', key: 'to',value: 'to', flag: 'to' },
        { text: 'Trinidad', key: 'tt',value: 'tt', flag: 'tt' },
        { text: 'Tunisia', key: 'tn',value: 'tn', flag: 'tn' },

        { text: 'Turkmenistan', key: 'tm',value: 'tm', flag: 'tm' },
        { text: 'Tuvalu', key: 'tv',value: 'tv', flag: 'tv' },
        { text: 'U.A.E.', key: 'ae',value: 'ae', flag: 'ae' },
        { text: 'Uganda', key: 'ug',value: 'ug', flag: 'ug' },
        { text: 'Ukraine', key: 'ua',value: 'ua', flag: 'ua' },
        { text: 'United Kingdom', key: 'gb',value: 'gb', flag: 'gb'},
        { text: 'United States', key: 'us',value: 'us', flag: 'us' },
        { text: 'Uruguay', key: 'uy',value: 'uy', flag: 'uy' },
        { text: 'US Minor Islands', key: 'um',value: 'um', flag: 'um' },
        { text: 'US Virgin Islands', key: 'vi',value: 'vi', flag: 'vi' },
        { text: 'Uzbekistan', key: 'uz',value: 'uz', flag: 'uz' },
        { text: 'Vanuatu', key: 'vu',value: 'vu', flag: 'vu' },
        { text: 'Vatican City', key: 'va',value: 'va', flag: 'va' },
        { text: 'Venezuela', key: 've',value: 've', flag: 've' },
        { text: 'Vietnam', key: 'vn',value: 'vn', flag: 'vn' },

        { text: 'Wallis and Futuna', key: 'wf',value: 'wf', flag: 'wf' },
        { text: 'Western Sahara', key: 'eh',value: 'eh', flag: 'eh' },
        { text: 'Yemen', key: 'ye',value: 'ye', flag: 'ye' },
        { text: 'Zambia', key: 'zm',value: 'zm', flag: 'zm' },
        { text: 'Zimbabwe', key: 'zw',value: 'zw', flag: 'zw' },
      ]

export default dataPart;